// GENERATED by scripts/gen-calibration-manifest.mjs — do not edit by hand.
//
// Regenerate after adding, removing, renaming, or re-baselining a pose:
//   make web-app-manifest
//
// Structure only. Pose values are deliberately absent — the page reads live
// frame positions off the running machine instead.

import type { MachineManifest } from "./calibration";

export const MANIFEST: MachineManifest[] = [
  {
    "machine": "cappuccina-main",
    "partId": "5be4df6e-b9ae-4a5f-acc0-e258d51be17d",
    "generatedAt": "2026-08-28T16:17:18.255Z",
    "frames": [
      {
        "frame": "filter",
        "switch": "filter-poses-switch",
        "configure": [
          "cleaning_brush_active",
          "cleaning_scrapper_active",
          "coffee_in",
          "decaf_grinder_activate",
          "grinder_activate",
          "home",
          "purge_approach",
          "tamper_activate"
        ],
        "derived": [
          {
            "pose": "approach_to_cleaning_brush",
            "baseline": "cleaning_brush_active"
          },
          {
            "pose": "approach_to_cleaning_scrapper",
            "baseline": "cleaning_scrapper_active"
          },
          {
            "pose": "close_to_cleaning",
            "baseline": "approach_to_cleaning_scrapper"
          },
          {
            "pose": "coffee_approach",
            "baseline": "coffee_in"
          },
          {
            "pose": "coffee_locked_final",
            "baseline": "coffee_in"
          },
          {
            "pose": "coffee_shake",
            "baseline": "coffee_in"
          },
          {
            "pose": "coffee_shake_left",
            "baseline": "coffee_in"
          },
          {
            "pose": "decaf_grinder_approach",
            "baseline": "decaf_grinder_activate"
          },
          {
            "pose": "grinder_approach",
            "baseline": "grinder_activate"
          },
          {
            "pose": "purge_press",
            "baseline": "purge_approach"
          },
          {
            "pose": "tamper_approach",
            "baseline": "tamper_activate"
          }
        ]
      },
      {
        "frame": "grip-point",
        "switch": "claws-position-switch",
        "configure": [
          "coffee_button_on",
          "coffee_locked_final",
          "cup_observe",
          "cup_ready_for_coffee",
          "espresso_button_approach",
          "ice_machine_dispense",
          "staging"
        ],
        "derived": [
          {
            "pose": "coffee_button_approach",
            "baseline": "coffee_button_on"
          },
          {
            "pose": "coffee_button_off",
            "baseline": "coffee_button_on"
          },
          {
            "pose": "cup_under_machine_approach",
            "baseline": "cup_ready_for_coffee"
          },
          {
            "pose": "espresso_button_press",
            "baseline": "espresso_button_approach"
          },
          {
            "pose": "filter_released",
            "baseline": "coffee_locked_final"
          },
          {
            "pose": "ice_machine_approach",
            "baseline": "ice_machine_dispense"
          },
          {
            "pose": "lungo_button_approach",
            "baseline": "espresso_button_approach"
          },
          {
            "pose": "lungo_button_press",
            "baseline": "lungo_button_approach"
          },
          {
            "pose": "pour",
            "baseline": "pour_approach"
          },
          {
            "pose": "pour_approach",
            "baseline": "staging"
          },
          {
            "pose": "staging_approach",
            "baseline": "staging"
          }
        ]
      },
      {
        "frame": "cam",
        "switch": "camera-observation-switch",
        "configure": [
          "cup_observe",
          "cup_observe_2",
          "cup_observe_3"
        ],
        "derived": []
      },
      {
        "frame": "cam",
        "switch": "glass-observe-switch",
        "configure": [
          "glass_observe"
        ],
        "derived": []
      }
    ]
  }
];
